services:
  postgres:
    image: postgres:15.6
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: tcms_postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tcms

  backend:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python /app/src/manage.py runserver 0.0.0.0:8000
    container_name: tcms_backend
    networks:
      - tcms

volumes:
  postgres_data:

networks:
  tcms: