"""initial

Revision ID: 69c277d189b2
Revises: 
Create Date: 2025-09-18 18:35:43.749812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c277d189b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('last_name', sa.String(length=50), nullable=False, comment='Фамилия'),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment='Имя'),
    sa.Column('patronymic', sa.String(length=50), nullable=True, comment='Отчество'),
    sa.Column('date_of_birth', sa.Date(), nullable=False, comment='Дата рождения'),
    sa.Column('gender', sa.Enum('male', 'female', name='gendertypes'), nullable=False, comment='Пол'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='Email'),
    sa.Column('phone_number', sa.String(length=12), nullable=False, comment='Номер телефона'),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Суперюзер'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Активен'),
    sa.Column('join_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата регистрации'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_patronymic'), 'users', ['patronymic'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_patronymic'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
